cppVersion = -std=c++20
compilerType = g++

all: comp_t0 comp_t1 comp_t2

comp_t0:
	$(compilerType) $(cppVersion) a0ReadingFile_t0.cpp -o a0.exe
comp_t1:
	$(compilerType) $(cppVersion) a1ReadingChar.cpp -o a1.exe
comp_t2:
	$(compilerType) $(cppVersion) a2ReadingCharLex.cpp -o a2.exe